version: '3.9'

services:

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: TPCC_BE
    ports:
      - 8080:3000
      - 9229:9229
    volumes:
      - /backend/app/node_modules
      - ./backend/src:/app/src
    networks:
      - default
      - database-nw
    external_links:
      - global-postgres
networks:
  database-nw:
    external: true
  # web:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: TPCC_FE
  #   ports: 
  #     - 3000:3000
  #   depends_on:
  #     - api
  #   volumes:
  #     - /frontend/app/node_modules
  #     - ./frontend/src:/app/src
  #     - ./frontend/public:/app/public
  #   command: yarn start